version: '3.8'
services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: sail-8.0/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8000:8000" # Map container port 8000 to host port 8000
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      LARAVEL_SAIL: 1
      APP_NAME: '${APP_NAME:-Laravel}'
      DB_CONNECTION: '${DB_CONNECTION:-mysql}'
      DB_HOST: '${DB_HOST:-mysql}'
      DB_PORT: '${DB_PORT:-3306}'
      DB_DATABASE: '${DB_DATABASE:-laravel}'
      DB_USERNAME: '${DB_USERNAME:-root}'
      DB_PASSWORD: '${DB_PASSWORD:-root}'
      CACHE_DRIVER: '${CACHE_DRIVER:-file}'
      QUEUE_CONNECTION: '${QUEUE_CONNECTION:-sync}'
    volumes:
      - './:/var/www/html' # Map current directory to container's web root
    networks:
      - sail
    depends_on:
      - mysql
  mysql:
    image: 'mysql/mysql-server:5.7'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_DATABASE: '${DB_DATABASE:-laravel}'
      MYSQL_USER: '${DB_USERNAME:-root}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-root}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: "exit 0"
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
